services:
  # Backend API service
  - type: web
    name: brand-resonance-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9.0
    autoDeploy: true
